2021-07-19 23:01:35 database: close
org.h2.message.DbException: File corrupted while reading record: "wrong checksum". Possible solution: use the recovery tool [90030-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.store.PageStore.getPage(PageStore.java:758)
	at org.h2.store.PageStore.compact(PageStore.java:711)
	at org.h2.store.PageStore.compact(PageStore.java:539)
	at org.h2.engine.Database.closeOpenFilesAndUnlock(Database.java:1408)
	at org.h2.engine.Database.close(Database.java:1336)
	at org.h2.engine.Database.removeSession(Database.java:1219)
	at org.h2.engine.Session.close(Session.java:889)
	at org.h2.jdbc.JdbcConnection.close(JdbcConnection.java:411)
	at scala.meta.internal.metals.Tables.cancel(Tables.scala:33)
	at scala.meta.internal.metals.Cancelable$.$anonfun$cancelAll$1(Cancelable.scala:27)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.meta.internal.metals.Cancelable$.cancelAll(Cancelable.scala:26)
	at scala.meta.internal.metals.MutableCancelable.cancel(MutableCancelable.scala:19)
	at scala.meta.internal.metals.MetalsLanguageServer.cancel(MetalsLanguageServer.scala:72)
	at scala.meta.internal.metals.MetalsLanguageServer.shutdown(MetalsLanguageServer.scala:522)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:192)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: File corrupted while reading record: "wrong checksum". Possible solution: use the recovery tool [90030-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 38 more
